### ISSUE TITLE
on click event

### ISSUE THREAD

**Issue by vandermeerjl** [dcdeiv/simple-sidebar#6]
Hi!

I am trying to do an on click event that changes that toggles the menu button into an x but it only changes once. When the sidebar is open and you click the icon it does not toggle back to the original form. Is there a way to trigger the side bar to open by an on click event and leave the 'opener' as undefined? also is there an on open end event to the sidebar?

**Comment by vandermeerjl** [comment]
also is there any way to get rid of the mask completely? the plugin automatically adds on whether I want it or not...

**Comment by dcdeiv** [comment]
Actually I don't understand what you wish from this plugin. You wish to turn your menu button into an X when the sidebar is opened and to turn back to the first icon when it is closed?
I don't think I am going to allow this because I am not able in the first place, but I will try to make a version without the mask.

**Comment by dcdeiv** [comment]
I partially fullfilled what you wish. I am not providing an **on click** event but I am providing an option to disable the mask.
Please, see the new release: #v2.0.0
