### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by laupkram** [dcdeiv/simple-sidebar#9]
Your source code is under GPL license, is there anyway you can dual license it to MIT? 
Thanks:)

**Comment by dcdeiv** [comment]
I've never understood how licensing properely works. However I don't think it is possible to release this plugin with a dual license because GPL and MIT are not compatible, plus I don't really trust MIT license.

And [this topic](http://stackoverflow.com/questions/3902754/mit-vs-gpl-license) really confuses me.

**Comment by dcdeiv** [comment]
http://choosealicense.com/licenses/

**Comment by dcdeiv** [comment]
I've reopened this issue because I am working on the next release which will be dual licensed under MIT and GPL-2.0.

**Comment by dcdeiv** [comment]
From v2.8.0 simple-sidebar will be released under MIT and GPL-2.0 licenses.
